apiVersion: v1
kind: Service
metadata:
  name: mini-project-service
spec:
  selector:
    app: mini-project
  ports:
    - protocol: TCP
      port: 7000  
      targetPort: 7000
      nodePort: 30001 
  type: NodePort
